/*
1Click Swap API

API for One-Click Swaps

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package oneclick

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SubmitDepositTxResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubmitDepositTxResponse{}

// SubmitDepositTxResponse struct for SubmitDepositTxResponse
type SubmitDepositTxResponse struct {
	// Quote response from original request
	QuoteResponse QuoteResponse `json:"quoteResponse"`
	Status        string        `json:"status"`
	// Last time the state was updated
	UpdatedAt time.Time `json:"updatedAt"`
	// Details of actual swaps and withdrawals
	SwapDetails SwapDetails `json:"swapDetails"`
}

type _SubmitDepositTxResponse SubmitDepositTxResponse

// NewSubmitDepositTxResponse instantiates a new SubmitDepositTxResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitDepositTxResponse(quoteResponse QuoteResponse, status string, updatedAt time.Time, swapDetails SwapDetails) *SubmitDepositTxResponse {
	this := SubmitDepositTxResponse{}
	this.QuoteResponse = quoteResponse
	this.Status = status
	this.UpdatedAt = updatedAt
	this.SwapDetails = swapDetails
	return &this
}

// NewSubmitDepositTxResponseWithDefaults instantiates a new SubmitDepositTxResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitDepositTxResponseWithDefaults() *SubmitDepositTxResponse {
	this := SubmitDepositTxResponse{}
	return &this
}

// GetQuoteResponse returns the QuoteResponse field value
func (o *SubmitDepositTxResponse) GetQuoteResponse() QuoteResponse {
	if o == nil {
		var ret QuoteResponse
		return ret
	}

	return o.QuoteResponse
}

// GetQuoteResponseOk returns a tuple with the QuoteResponse field value
// and a boolean to check if the value has been set.
func (o *SubmitDepositTxResponse) GetQuoteResponseOk() (*QuoteResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuoteResponse, true
}

// SetQuoteResponse sets field value
func (o *SubmitDepositTxResponse) SetQuoteResponse(v QuoteResponse) {
	o.QuoteResponse = v
}

// GetStatus returns the Status field value
func (o *SubmitDepositTxResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SubmitDepositTxResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SubmitDepositTxResponse) SetStatus(v string) {
	o.Status = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *SubmitDepositTxResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *SubmitDepositTxResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *SubmitDepositTxResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetSwapDetails returns the SwapDetails field value
func (o *SubmitDepositTxResponse) GetSwapDetails() SwapDetails {
	if o == nil {
		var ret SwapDetails
		return ret
	}

	return o.SwapDetails
}

// GetSwapDetailsOk returns a tuple with the SwapDetails field value
// and a boolean to check if the value has been set.
func (o *SubmitDepositTxResponse) GetSwapDetailsOk() (*SwapDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SwapDetails, true
}

// SetSwapDetails sets field value
func (o *SubmitDepositTxResponse) SetSwapDetails(v SwapDetails) {
	o.SwapDetails = v
}

func (o SubmitDepositTxResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubmitDepositTxResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["quoteResponse"] = o.QuoteResponse
	toSerialize["status"] = o.Status
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["swapDetails"] = o.SwapDetails
	return toSerialize, nil
}

func (o *SubmitDepositTxResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"quoteResponse",
		"status",
		"updatedAt",
		"swapDetails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubmitDepositTxResponse := _SubmitDepositTxResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubmitDepositTxResponse)

	if err != nil {
		return err
	}

	*o = SubmitDepositTxResponse(varSubmitDepositTxResponse)

	return err
}

type NullableSubmitDepositTxResponse struct {
	value *SubmitDepositTxResponse
	isSet bool
}

func (v NullableSubmitDepositTxResponse) Get() *SubmitDepositTxResponse {
	return v.value
}

func (v *NullableSubmitDepositTxResponse) Set(val *SubmitDepositTxResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitDepositTxResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitDepositTxResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitDepositTxResponse(val *SubmitDepositTxResponse) *NullableSubmitDepositTxResponse {
	return &NullableSubmitDepositTxResponse{value: val, isSet: true}
}

func (v NullableSubmitDepositTxResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitDepositTxResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
